version: "3.9"

volumes:
  sqlite_data:

services:
  api:
    build:
      context: nextgen/backend
      target: dev
    environment:
      - STATE_DIR=/app/data
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    # Allow SYN scan with -sS inside container; otherwise use -sT
    cap_add:
      - NET_RAW
      - NET_ADMIN
    profiles: ["dev"]

  web:
    build:
      context: nextgen/frontend
      target: dev
    environment:
      - PUBLIC_API_BASE=http://api:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:80"
    depends_on:
      - api
    profiles: ["dev"]

  api-prod:
    build:
      context: nextgen/backend
      target: prod
    environment:
      - STATE_DIR=/app/data
    volumes:
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    profiles: ["prod"]

  web-prod:
    build:
      context: nextgen/frontend
      target: prod
      args:
        PUBLIC_API_BASE: http://api-prod:8000
    environment:
      - PUBLIC_API_BASE=http://api-prod:8000
    ports:
      - "8080:4173"
    depends_on:
      - api-prod
    profiles: ["prod"]
